export interface GoogleData {(
    kind: string,
    title: string,
    htmlTitle: string,
    link: string,
    displayLink: string,
    snippet: string,
    htmlSnippet: string,
    cacheId: string,
    formattedUrl: string,
    htmlFormattedUrl: string,
    pagemap: {
        metatags: {
            "theme-color": string,
            "og:type": string,
            "apple-mobile-web-app-status-bar-style": string,
            "og:site_name": string,
            "twitter:site": string,
            viewport: string,
            "apple-mobile-web-app-capable": string,
            "og:title": string,
            "og:url": string,
            "msapplication-navbutton-color": string,
            "og:description": string,
        },
        cse_thumbnail: undefined,
        cse_image: undefined,
    },
)}
